# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VariableSelectionUnknowCompFMR <- function(Num.of.iterations, Num.of.iterations.Inside, Max.num.of.groups, list.Data, list.InitialValues, list.GivenValues, bool.Robust, bool.RJMCMC) {
    .Call("WorkUnknownCompFMR", PACKAGE = 'UnknownCompFMR', Num.of.iterations, Num.of.iterations.Inside, Max.num.of.groups, list.Data, list.InitialValues, list.GivenValues, 
    	bool.Robust, bool.RJMCMC)
}

